export const database = [
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: true,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: true,
    isImportant: true,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "test@gmail.com",
    senderName: "Test",
    subject: "An email",
    body: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: true,
    isDraft: false,
    isSpam: false,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "spam@gmail.com",
    senderName: "Spam",
    subject: "An email",
    body: "This is one of the most common types of spam. I bet you’ve already received several unsolicited emails offering products and services, such as weight loss pills and tennis offers. In many cases it may be a scam but the offer may also be real.",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: true,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "spam2@gmail.com",
    senderName: "Spam 2",
    subject: "An email",
    body: "This is one of the most common types of spam. I bet you’ve already received several unsolicited emails offering products and services, such as weight loss pills and tennis offers. In many cases it may be a scam but the offer may also be real.",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: true,
    isThrash: false,
    isSent: false,
  },
  {
    sender: "thrash@gmail.com",
    senderName: "Thrash",
    subject: "An email",
    body: "Deleted mail",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: true,
    isSent: false,
  },
  {
    sender: "thrash@gmail.com",
    senderName: "Thrash",
    subject: "An email",
    body: "Deleted mail",
    sentOn: "Thu, 4 Mar 2010 15:35:32",
    isRead: false,
    isImportant: false,
    isDraft: false,
    isSpam: false,
    isThrash: true,
    isSent: false,
  },
];
